lib/shift73k_web/router.ex
defmodule Shift73kWeb.Router do
  use Shift73kWeb, :router
  import Shift73kWeb.UserAuth
  alias Shift73kWeb.EnsureRolePlug

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {Shift73kWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :user do
    plug(EnsureRolePlug, [:admin, :manager, :user])
  end

  pipeline :manager do
    plug(EnsureRolePlug, [:admin, :manager])
  end

  pipeline :admin do
    plug(EnsureRolePlug, :admin)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser])

    get("/", Redirector, to: "/assign")
  end

  # Other scopes may use custom stacks.
  # scope "/api", Shift73kWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)
      live_dashboard("/dashboard", metrics: Shift73kWeb.Telemetry)
    end
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    # session routes, irrelevant if user is authenticated
    get("/users/register", UserRegistrationController, :new)
    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser, :require_authenticated_user])

    # user settings (change email, password, calendar week start, etc)
    live("/users/settings", UserLive.Settings, :edit)

    # confirm email by token
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser])

    # session paths
    delete("/users/log_out", UserSessionController, :delete)
    get("/users/force_logout", UserSessionController, :force_logout)
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :confirm)

    # ics/ical route for user's shifts
    get("/ics/:slug", UserShiftsIcsController, :index)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser, :require_authenticated_user, :user])

    live "/templates", ShiftTemplateLive.Index, :index
    live "/templates/new", ShiftTemplateLive.Index, :new
    live "/templates/:id/edit", ShiftTemplateLive.Index, :edit
    live "/templates/:id/clone", ShiftTemplateLive.Index, :clone

    live "/assign", ShiftAssignLive.Index, :index

    live "/shifts", ShiftLive.Index, :index

    get "/csv", UserShiftsCsvController, :new
    post "/csv", UserShiftsCsvController, :export

    live "/import", ShiftImportLive.Index, :index
  end

  # scope "/", Shift73kWeb do
  #   pipe_through([:browser, :require_authenticated_user, :admin])
  # end

  # Users Management
  scope "/users", Shift73kWeb do
    pipe_through([:browser, :require_authenticated_user, :manager, :require_email_confirmed])

    live("/", UserManagementLive.Index, :index)
    live("/new", UserManagementLive.Index, :new)
    live("/edit/:id", UserManagementLive.Index, :edit)
    # resources "/", UserManagementController, only: [:new, :create, :edit, :update]
  end
end

lib/shift73k_web/views/layout_view.ex
defmodule Shift73kWeb.LayoutView do
  use Shift73kWeb, :view

  alias Shift73k.Accounts.User
  alias Shift73kWeb.Roles

  def nav_link_opts(conn, opts) do
    case Keyword.get(opts, :to) == Phoenix.Controller.current_path(conn) do
      false -> opts
      true -> Keyword.update(opts, :class, "active", fn c -> "#{c} active" end)
    end
  end

  def alert_kinds do
    [
      success: "alert-success",
      info: "alert-info",
      error: "alert-danger",
      warning: "alert-warning",
      primary: "alert-primary",
      secondary: "alert-secondary"
    ]
  end
end

lib/shift73k_web/templates/layout/navbar/_shifts_menu.html.eex
<li class="nav-item dropdown">

  <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownUserMenu" data-bs-toggle="dropdown" aria-expanded="false">
    <%= icon_div @conn, "bi-calendar2", [class: "icon baseline me-1"] %>
    Shifts
  </a>

  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownUserMenu">

    <li>
      <%= link nav_link_opts(@conn, to: Routes.shift_assign_index_path(@conn, :index), class: "dropdown-item") do %>
        <%= icon_div @conn, "bi-calendar2-plus", [class: "icon baseline me-1"] %>
        Schedule Shifts
      <% end %>
    </li>
    <li>
      <%= link nav_link_opts(@conn, to: Routes.shift_index_path(@conn, :index), class: "dropdown-item") do %>
        <%= icon_div @conn, "bi-card-list", [class: "icon baseline me-1"] %>
        My Scheduled Shifts
      <% end %>
    </li>
    <li>
      <%= link nav_link_opts(@conn, to: Routes.shift_template_index_path(@conn, :index), class: "dropdown-item") do %>
        <%= icon_div @conn, "bi-clock-history", [class: "icon baseline me-1"] %>
        My Shift Templates
      <% end %>
    </li>

    <li><hr class="dropdown-divider"></li>
<%# user_shifts_csv_path %>
    <li>
      <%= link nav_link_opts(@conn, to: Routes.user_shifts_csv_path(@conn, :new), class: "dropdown-item") do %>
        <%= icon_div @conn, "bi-file-earmark-spreadsheet", [class: "icon baseline me-1"] %>
        CSV Export
      <% end %>
    </li>
    <li>
      <%= link nav_link_opts(@conn, to: Routes.shift_import_index_path(@conn, :index), class: "dropdown-item") do %>
        <%= icon_div @conn, "bi-box-arrow-in-left", [class: "icon baseline me-1"] %>
        iCal Import
      <% end %>
    </li>

  </ul>

</li>

lib/shift73k_web/templates/layout/navbar/_user_menu.html.eex
<li class="nav-item dropdown">

  <a href="#" class="nav-link dropdown-toggle" id="navbarDropdownUserMenu" data-bs-toggle="dropdown" aria-expanded="false">
    <%= icon_div @conn, "bi-person-circle", [class: "icon baseline me-1"] %>
    <%= @current_user && "Hello!" || "Hello?" %>
  </a>

  <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownUserMenu">

    <li><%= content_tag :span, @current_user.email, class: "dropdown-item-text" %></li>
    <li><hr class="dropdown-divider"></li>
    <%= if Roles.can?(@current_user, %User{}, :index) do %>
      <li>
        <%= link nav_link_opts(@conn, to: Routes.user_management_index_path(@conn, :index), class: "dropdown-item") do %>
          <%= icon_div @conn, "bi-people", [class: "icon baseline me-1"] %>
          Users
        <% end %>
      </li>
      <li><hr class="dropdown-divider"></li>
    <% end %>
    <li>
      <%= link nav_link_opts(@conn, to: Routes.user_settings_path(@conn, :edit), class: "dropdown-item") do %>
        <%= icon_div @conn, "bi-sliders", [class: "icon baseline me-1"] %>
        Settings
      <% end %>
    </li>
    <li>
      <%= link nav_link_opts(@conn, to: Routes.user_session_path(@conn, :delete), method: :delete, class: "dropdown-item") do %>
        <%= icon_div @conn, "bi-door-closed", [class: "icon baseline me-1"] %>
        Log out
      <% end %>
    </li>

  </ul>

</li>