lib/shift73k_web/router.ex
defmodule Shift73kWeb.Router do
  use Shift73kWeb, :router
  import Shift73kWeb.UserAuth
  alias Shift73kWeb.EnsureRolePlug

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_live_flash)
    plug(:put_root_layout, {Shift73kWeb.LayoutView, :root})
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
    plug(:fetch_current_user)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  pipeline :user do
    plug(EnsureRolePlug, [:admin, :manager, :user])
  end

  pipeline :manager do
    plug(EnsureRolePlug, [:admin, :manager])
  end

  pipeline :admin do
    plug(EnsureRolePlug, :admin)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser])

    get("/", Redirector, to: "/assign")
  end

  # Other scopes may use custom stacks.
  # scope "/api", Shift73kWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through(:browser)
      live_dashboard("/dashboard", metrics: Shift73kWeb.Telemetry)
    end
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser, :redirect_if_user_is_authenticated])

    # session routes, irrelevant if user is authenticated
    get("/users/register", UserRegistrationController, :new)
    get("/users/log_in", UserSessionController, :new)
    post("/users/log_in", UserSessionController, :create)
    get("/users/reset_password", UserResetPasswordController, :new)
    post("/users/reset_password", UserResetPasswordController, :create)
    get("/users/reset_password/:token", UserResetPasswordController, :edit)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser, :require_authenticated_user])

    # user settings (change email, password, calendar week start, etc)
    live("/users/settings", UserLive.Settings, :edit)

    # confirm email by token
    get("/users/settings/confirm_email/:token", UserSettingsController, :confirm_email)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser])

    # session paths
    delete("/users/log_out", UserSessionController, :delete)
    get("/users/force_logout", UserSessionController, :force_logout)
    get("/users/confirm", UserConfirmationController, :new)
    post("/users/confirm", UserConfirmationController, :create)
    get("/users/confirm/:token", UserConfirmationController, :confirm)

    # ics/ical route for user's shifts
    get("/ics/:slug", UserShiftsIcsController, :index)
  end

  scope "/", Shift73kWeb do
    pipe_through([:browser, :require_authenticated_user, :user])

    live "/templates", ShiftTemplateLive.Index, :index
    live "/templates/new", ShiftTemplateLive.Index, :new
    live "/templates/:id/edit", ShiftTemplateLive.Index, :edit
    live "/templates/:id/clone", ShiftTemplateLive.Index, :clone

    live "/assign", ShiftAssignLive.Index, :index

    live "/shifts", ShiftLive.Index, :index

    get "/csv", UserShiftsCsvController, :new
    post "/csv", UserShiftsCsvController, :export

    live "/import", ShiftImportLive.Index, :index
  end

  # scope "/", Shift73kWeb do
  #   pipe_through([:browser, :require_authenticated_user, :admin])
  # end

  # Users Management
  scope "/users", Shift73kWeb do
    pipe_through([:browser, :require_authenticated_user, :manager, :require_email_confirmed])

    live("/", UserManagementLive.Index, :index)
    live("/new", UserManagementLive.Index, :new)
    live("/edit/:id", UserManagementLive.Index, :edit)
    # resources "/", UserManagementController, only: [:new, :create, :edit, :update]
  end
end

lib/shift73k_web/controllers/user_session_controller.ex
defmodule Shift73kWeb.UserSessionController do
  use Shift73kWeb, :controller

  alias Phoenix.HTML
  alias Shift73k.Accounts
  alias Shift73k.Accounts.User
  alias Shift73kWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => %{"email" => email, "password" => password} = user_params}) do
    if user = Accounts.get_user_by_email_and_password(email, password) do
      conn
      |> put_flash(
        :info,
        HTML.raw("Welcome back, #{user.email} &mdash; you were logged in successfuly.")
      )
      |> UserAuth.log_in_user(user, user_params)
    else
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def create(conn, %{"user" => %{"params_token" => token} = user_params}) do
    with {:ok, params} <- Phoenix.Token.decrypt(Shift73kWeb.Endpoint, "login_params", token),
         %User{} = user <- Accounts.get_user(params.user_id) do
      conn
      |> collect_messages(params.messages)
      |> put_session(:user_return_to, params.user_return_to)
      |> UserAuth.log_in_user(user, Map.put_new(user_params, "remember_me", "false"))
    else
      _ -> render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  defp collect_messages(conn, messages) do
    Enum.reduce(messages, conn, fn {type, msg}, acc -> put_flash(acc, type, msg) end)
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end

  def force_logout(conn, _params) do
    conn
    |> put_flash(
      :info,
      "You were logged out. Please login again to continue using our application."
    )
    |> UserAuth.log_out_user()
  end
end

lib/shift73k_web/views/user_session_view.ex
defmodule Shift73kWeb.UserSessionView do
  use Shift73kWeb, :view
  alias Shift73k.Accounts.User
end

lib/shift73k_web/templates/user_session/new.html.eex
<div class="row justify-content-center">
  <div class="col-11 col-sm-8 col-md-6 col-lg-5 col-xl-4 col-xxl-3">

  <h2>
    <%= icon_div @conn, "bi-door-open", [class: "icon baseline"] %>
    Log in
  </h2>
  <p class="lead">Who goes there?</p>

  <%= form_for @conn, Routes.user_session_path(@conn, :create), [as: :user, class: "needs-validation", novalidate: true], fn f -> %>
    <%= if @error_message do %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= @error_message %>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    <% end %>

    <%= label f, :email, class: "form-label" %>
    <div class="inner-addon left-addon mb-3">
      <%= icon_div @conn, "bi-at", [class: "icon is-left text-muted fs-5"] %>
      <%= email_input f, :email,
          class: "form-control",
          placeholder: "e.g., babka@73k.us",
          maxlength: User.max_email,
          required: true
        %>
      <span class="invalid-feedback">must be a valid email address</span>
    </div>

    <%= label f, :password, class: "form-label" %>
    <div class="inner-addon left-addon mb-3">
      <%= icon_div @conn, "bi-lock", [class: "icon is-left text-muted fs-5"] %>
      <%= password_input f, :password,
          class: "form-control",
          required: true
        %>
      <span class="invalid-feedback">password is required</span>
    </div>

    <div class="form-check mb-3 no-valid-style">
      <%= checkbox f, :remember_me, class: "form-check-input" %>
      <%= label f, :remember_me, "Keep me logged in for 60 days", class: "form-check-label" %>
    </div>

    <div class="mb-3">
      <%= submit "Log in", class: "btn btn-primary" %>
    </div>

  <% end %>

  <p>
    <%= link "Register", to: Routes.user_registration_path(@conn, :new) %> |
    <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new) %>
  </p>

  </div>
</div>